export const ENVIRONMENT_VARIABLES = {
    NODE_ENV: 'NODE_ENV',
    HOST: 'HOST',
    PORT: 'PORT',
    REQUEST_BODY_LIMIT: 'REQUEST_BODY_LIMIT',
    JWT_SECRET: 'JWT_SECRET',
    ACCESS_TOKEN_EXPIRES_IN: 'ACCESS_TOKEN_EXPIRES_IN',
    REFRESH_TOKEN_EXPIRES_IN: 'REFRESH_TOKEN_EXPIRES_IN',
    DATABASE_URL: 'DATABASE_URL',
    AWS_REGION: 'AWS_REGION',
    S3_BUCKET: 'S3_BUCKET',
    S3_PRESIGN_EXPIRES_IN: 'S3_PRESIGN_EXPIRES_IN',
    MAX_LEAD_IMPORT_FILE_SIZE: 'MAX_LEAD_IMPORT_FILE_SIZE',
    MAX_LEAD_EXPORT_ROWS: 'MAX_LEAD_EXPORT_ROWS'
} as const

export const ALLOWED_ENVIRONMENTS = ['development', 'test', 'production'] as const

